# Generated by Django 5.2.3 on 2025-07-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgetApp', '0002_additionalproduct_product_address_cart_order_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalproduct',
            name='name',
        ),
        migrations.AddField(
            model_name='additionalproduct',
            name='brand',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
