# Generated by Django 5.2.3 on 2025-06-28 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgetApp', '0003_remove_product_image_url_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_accessory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_best_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_latest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new_arrival',
            field=models.BooleanField(default=False),
        ),
    ]
