# Generated by Django 5.2.3 on 2025-06-28 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgetApp', '0004_product_is_accessory_product_is_best_seller_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_accessory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_best_seller',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_latest',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_new_arrival',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.CreateModel(
            name='ProductPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_note', models.CharField(max_length=100)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='gadgetApp.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='gadgetApp.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.CharField(max_length=50)),
                ('processor', models.CharField(max_length=50)),
                ('storage', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='gadgetApp.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.IntegerField()),
                ('bought_last_month', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('review_count', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='gadgetApp.product')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='gadgetApp.productvariant')),
            ],
        ),
    ]
